spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  jpa:
    show-sql: false
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/bitstwinkle_jelly?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useCompression=true
    username: bitstwinkle
    password: bitstwinkle
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
  logging:
    level:
      com.*.facade.*: INFO
      tech.*.facade.*: INFO


jelly:
  aliyun:
    access-key: XXXXXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXX
    mq:
      default-instance: XXXXXXXXXXXXXXXXXXXXXX

#  timingtask:
#    # 未处理订单定时任务
#    OrderProcess:
#      group: ORDER_PROCESS_UNIT
#      code: PREORDER_PROCESS
#      cron: 1-2 0/1 * * * ? *


